apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: YWRtaW46JGFwcjEkWDRodHZXWWskb3Q5WnY1Mno1MExyeHBicDVreDlxMAp1c2VyMTokYXByMSRuZkxGbnEzcyRlQ3dpVDRvWmpFRW9XeHBsMmNKdjkvCnVzZXIyOiRhcHIxJHQxT1pBLmVpJHhSV29wY0ZBd0haMWZ4NVM5V1ouNS8KdXNlcjM6JGFwcjEkc3p6dVo4TnAkaUx0R29lRlhybm9FamJHL211MWEvLwp1c2VyNDokYXByMSRKUk1wR2tGOSRPRWVhMlVXVDJ2VjNRZnJVUmx1WksvCnVzZXI1OiRhcHIxJHUwLmJPUWxRJGZQdUZYYW5CL254QlFIemdpaFNYODEK
