apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-tools

bases:
# Nexus
- https://github.com/redhat-canada-gitops/catalog/nexus2/base
# Sonarqube
- https://github.com/redhat-canada-gitops/catalog/sonarqube8/overlays/plugins

resources:
- namespace.yaml