apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../../manifests/configs/consolelinks/base

patches:
- target:
    group: console.openshift.io
    version: v1
    kind: ConsoleLink
    name: argocd
  path: patch-link.yaml