apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
  labels:
    gitops.ownedBy: cluster-config
  name: config-container-security
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: container-security-operator/overlays/stable-3.6
    repoURL: https://github.com/gnunn1/gitops-catalog.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true