# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: letsencrypt-job

bases:
- github.com/redhat-cop/gitops-catalog/letsencrypt-certs/base
resources:
- sealed-cloud-dns-credentials.yaml