apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Encrypt/Descrypt secrets to support gitops processes
    openshift.io/display-name: Sealed Secrets
  name: sealed-secrets
---
apiVersion: v1
data:
  PASS: cGFzczEyMw==
  USER: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: myapp-secret
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    gitops.ownedBy: cluster-config
  name: cluster-config-manager
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/overlays/home/argocd/apps
    repoURL: https://github.com/hupiper/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
