apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-pipeline-operator
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: openshift-pipelines-operator/overlays/ocp-4.8
    repoURL: https://github.com/redhat-canada-gitops/catalog.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false