apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-web-terminal-operator
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  ignoreDifferences:
  - group: workspace.devfile.io
    kind: DevWorkspace
    jsonPointers:
    - /spec/started
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: web-terminal-operator/overlays/aggregate
    repoURL: https://github.com/hupiper/catalog.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
