- op: add
  path: /users/-
  value: "kubeadmin"
- op: add
  path: /users/-
  value: "opentlc-mgr"
- op: add
  path: /users/-
  value: "admin"
- op: add
  path: /users/-
  value: "mdunnett@redhat.com" 