apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
  labels:
    gitops.ownedBy: cluster-config
  name: config-compliance-operator
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: compliance-operator/aggregate/scheduled
    repoURL: https://github.com/redhat-cop/gitops-catalog.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true