apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '51'
  labels:
    gitops.ownedBy: cluster-config
  name: tenant-product-catalog
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: tenants/product-catalog/argocd/applicationset/base
    repoURL: https://github.com/hupiper/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true