apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: product-catalog-gitops
spec:
  href: 'https://argocd-server-product-catalog-gitops.apps.ocp4.pokitoach.com'
  location: NamespaceDashboard
  # This text will appear in a box called "Launcher" under "namespace" or "project" in the web console
  text: Product Catalog Gitops
  namespaceDashboard:
    namespaces:
    # for these specific namespaces
    - product-catalog-gitops
    - product-catalog-dev
    - product-catalog-test
    - product-catalog-prod
    - product-catalog-cicd