# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-gitops

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

bases:
- ../../../../../components/apps/gitops-operator/base

resources:
- namespace.yaml
- operatorgroup.yaml
- product-catalog-project.yaml