apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- namespace.yaml
- operator-group.yaml
- ../../base