apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
spec:
  auth:
    identityProviderURL: 'https://sso-sso.apps.ocp4.pokitoach.com'
    identityProviderRealm: openshift
    identityProviderClientId: codeready-public
    externalIdentityProvider: true
  server:
    selfSignedCert: false
    gitSelfSignedCert: false
    tlsSupport: true