apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '31'
  name: config-dev-tools
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: dev-tools
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/dev-tools/overlays/default
    repoURL: https://github.com/hupiper/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true