- op: add
  path: /users/-
  value: "admin"
- op: add
  path: /users/-
  value: "user2"
- op: add
  path: /users/-
  value: "user3"
- op: add
  path: /users/-
  value: "user4"
- op: add
  path: /users/-
  value: "user5"