apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: argocdadmins
  path: argocdadmins-group-users.yaml
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: argocdusers
  path: argocdusers-group-users.yaml
# - target:
#     group: user.openshift.io
#     version: v1
#     kind: Group
#     name: developer
#   path: developer-group-users.yaml