# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

resources:
- https://github.com/redhat-cop/gitops-catalog/compliance-operator/overlays/scheduled

patchesStrategicMerge:
  - patch-scansetting.yaml