apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.8
  clusterID: 2a1b3b0d-7467-4ab8-a98a-feba88c8a348
  desiredUpdate:
    image: quay.io/openshift-release-dev/ocp-release@sha256:5d396ad7d5f3cb527580c735e87dfd3b853bbb531e7f03e3a184d0accc223cdf
    version: 4.8.13
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
