apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.8
  clusterID: bc9678af-6300-4d96-9507-f92bf0537223
  desiredUpdate:
    image: quay.io/openshift-release-dev/ocp-release@sha256:7047acb946649cc1f54d98a1c28dd7b487fe91479aa52c13c971ea014a66c8a8
    version: 4.8.5
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
