apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.9
  clusterID: 8c255305-9a90-454a-a025-6f755774eca1
  desiredUpdate:
    image: quay.io/openshift-release-dev/ocp-release@sha256:c91c0faf7ae3c480724a935b3dab7e5f49aae19d195b12f3a4ae38f8440ea96b
    version: 4.9.8
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
