apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
  labels:
    gitops.ownedBy: cluster-config
  name: config-acs
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: acs-operator/overlays/aggregate
    repoURL: https://github.com/redhat-canada-gitops/catalog.git
    targetRevision: acs
  syncPolicy:
    automated:
      selfHeal: true