apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '4'
  labels:
    gitops.ownedBy: cluster-config
  name: config-authentication
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/configs/oauth/overlays/default
    repoURL: https://github.com/hupiper/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true