apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
  labels:
    gitops.ownedBy: cluster-config
  name: config-web-terminal-operator
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: web-terminal-operator/overlays/aggregate
    repoURL: https://github.com/redhat-canada-gitops/catalog.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true