apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackrox-central-service
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
       - name: app
         value: "rhacs/central-services"
       - name: imagePullSecrets.allowNone
         value: "true"
       - name: central.exposure.route.enabled
         value: "true"
    chart: rhacs
    repoURL: https://mirror.openshift.com/pub/rhacs/charts/
    targetRevision: 3.0.60.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true