apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '2'
  labels:
    gitops.ownedBy: cluster-config
  name: letsencrypt-certs
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/letsencrypt-certs/overlays/default
    repoURL: https://github.com/hupiper/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true