apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-cluster-namespaces-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-cluster-namespaces-job
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-cluster-namespaces-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-cluster-namespaces-job
subjects:
  - kind: ServiceAccount
    name: patch-cluster-namespaces-job