apiVersion: batch/v1
kind: Job
metadata:
  name: patch-cluster-namespaces-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-cli:v4.7
        command:
          - /bin/bash
          - -c
          - |
            SECRET=$(oc get secret -l argocd.argoproj.io/secret-type=cluster -o name)
            if [ -z "${SECRET}" ]; then
                echo "No secret was found, exiting with error"
                exit 1
            else
                echo "Patching secret: ${SECRET}"
            fi
            ENCODED=$(echo -n "$NAMESPACES" | base64 -w 0)
            PATCH="[{'op' : 'replace' ,'path' : '/data/namespaces' ,'value' : '${ENCODED}'}]"
            echo "Patching encoded namespaces with patch: ${PATCH}"
            oc patch ${SECRET} --type='json' -p="${PATCH}"
        env:
        - name: NAMESPACES
          value: ""
        imagePullPolicy: Always
        name: patch-cluster-namespaces-job
      serviceAccount: patch-cluster-namespaces-job
      serviceAccountName: patch-cluster-namespaces-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30