apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-sa-patch-job
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-crb-patch-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: storage-sa-patch-job
    namespace: openshift-image-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-reg-replicas
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: patch-reg-spec
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        command:
            - /bin/bash
            - -c
            - |

              oc patch config.imageregistry.operator.openshift.io/cluster --type=merge -p '{"spec":{"rolloutStrategy":"Recreate","replicas":1}}'
              oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'
              oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim:":"image-registry-storage"}}}}'
      restartPolicy: Never
      serviceAccountName: storage-sa-patch-job
  backoffLimit: 0