apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-image-registry

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- reg-pvc.yaml
- patch-reg-replicas.yaml