#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: patch-job
#  namespace: namespace-configuration-operator
#  annotations:
#    argocd.argoproj.io/hook: PreSync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: patch-namespaces
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - namespaces
#    verbs:
#      - get
#      - list
#      - patch
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: patch-job
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: patch-namespaces
#subjects:
#  - kind: ServiceAccount
#    name: patch-job
#    namespace: namespace-configuration-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-default-ns-multitenant
  namespace: namespace-configuration-operator
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: patch-default-ns-multitenant
        image: registry.redhat.io/openshift4/ose-cli:v4.4
        command:
            - /bin/bash
            - -c
            - |

              oc label namespace default 'network.openshift.io/policy-group=ingress' --overwrite
      restartPolicy: Never
      serviceAccountName: patch-job
  backoffLimit: 0
